<?php

    $conn = $GLOBALS['SQL_CONN'];   
    
    $PROPERTY_KEY = $_POST['PROPERTY_KEY'];
    $PROPERTY_IDENTIFIER = $_POST['PROPERTY_IDENTIFIER'];
    $PROPERTY_NAME = $_POST['PROPERTY_NAME'];
    $PROPERTY_PRICE = $_POST['PROPERTY_PRICE'];
    $PROPERTY_TYPE = $_POST['PROPERTY_TYPE'];
    $PROPERTY_STREET1_ADDRESS = $_POST['PROPERTY_STREET1_ADDRESS'];
    $PROPERTY_STREET2_ADDRESS = $_POST['PROPERTY_STREET2_ADDRESS'];
    $PROPERTY_CITY = $_POST['PROPERTY_CITY'];
    $PROPERTY_STATE = $_POST['PROPERTY_STATE'];
    $PROPERTY_COUNTRY = $_POST['PROPERTY_COUNTRY'];
    $PROPERTY_ZIP = $_POST['PROPERTY_ZIP'];
    $PROPERTY_AVAILABLE = $_POST['PROPERTY_AVAILABLE'];
    $PROPERTY_DATE = $_POST['PROPERTY_DATE'];
    
    $query = "insert into andrewsdreamllc.property values(' $PROPERTY_KEY','$PROPERTY_IDENTIFIER','$PROPERTY_NAME','$PROPERTY_NAME','$PROPERTY_STREET1_ADDRESS','$PROPERTY_STREET2_ADDRESS','$PROPERTY_CITY','$PROPERTY_STATE','$PROPERTY_COUNTRY','$PROPERTY_ZIP', $PROPERTY_AVAILABLE,NOW());";

    if (mysqli_query($conn, $query))
    {
        echo "New record created successfully";
    }
    else 
    {
        echo "Error: " . $conn . "<br>" . mysqli_error($conn);
    }

?>