<?php

    // Get SQL Connection object
    include 'ConnectToSQL.php';
    $conn = $GLOBALS['SQL_CONN'];  

    // There are three tables per property. Update each of them 
    $PROPERTY = json_decode($_POST['PAYLOAD']);
    
    
    $PROPERTY_KEY = $PROPERTY->PROPERTY_KEY;
    // $PROPERTY_IDENTIFIER = $PROPERTY->PROPERTY_IDENTIFIER;
    $PROPERTY_NAME = $PROPERTY->PROPERTY_NAME;
    $PROPERTY_PRICE = $PROPERTY->PROPERTY_PRICE;
    $PROPERTY_TYPE = $PROPERTY->PROPERTY_TYPE;
    $PROPERTY_STREET_ADDRESS1 = $PROPERTY->PROPERTY_STREET_ADDRESS1;
    $PROPERTY_STREET_ADDRESS2 = $PROPERTY->PROPERTY_STREET_ADDRESS2;
    $PROPERTY_CITY = $PROPERTY->PROPERTY_CITY;
    $PROPERTY_STATE = $PROPERTY->PROPERTY_STATE;
    $PROPERTY_COUNTRY = $PROPERTY->PROPERTY_COUNTRY;
    $PROPERTY_ZIP = $PROPERTY->PROPERTY_ZIP;
    //$PROPERTY_AVAILABLE = $PROPERTY->PROPERTY_AVAILABLE;
    
    $query = "UPDATE ANDREWSDREAMLLC.property SET 
             PROPERTY_NAME = '$PROPERTY_NAME',
             PROPERTY_PRICE = $PROPERTY_PRICE,
             PROPERTY_TYPE = '$PROPERTY_TYPE',
             PROPERTY_STREET_ADDRESS1 = '$PROPERTY_STREET_ADDRESS1',
             PROPERTY_STREET_ADDRESS2 = '$PROPERTY_STREET_ADDRESS2',
             PROPERTY_CITY = '$PROPERTY_CITY',
             PROPERTY_STATE = '$PROPERTY_STATE',
             PROPERTY_COUNTRY = '$PROPERTY_COUNTRY',
             PROPERTY_ZIP = $PROPERTY_ZIP,
             PROPERTY_DATE  = NOW()
            WHERE PROPERTY_KEY = $PROPERTY_KEY;";

    if (mysqli_query($conn, $query))
    {
        echo "Property updated";
    }
    else 
    {
        echo "Error: " . $conn . "<br>" . mysqli_error($conn);
    }

    $PROPERTY_SQUARE_FEET = $PROPERTY->PROPERTY_SQUARE_FEET;
    $PROPERTY_BED = $PROPERTY->PROPERTY_BED;
    $PROPERTY_BATH = $PROPERTY->PROPERTY_BATH;
    $PROPERTY_PARKING = $PROPERTY->PROPERTY_PARKING;
    $PROPERTY_PET_FRIENDLY = $PROPERTY->PROPERTY_PET_FRIENDLY;
    $PROPERTY_ELECTRICITY = $PROPERTY->PROPERTY_ELECTRICITY;
    $PROPERTY_WATER_SEWAGE_TRASH = $PROPERTY->PROPERTY_WATER_SEWAGE_TRASH;
    $PROPERTY_LEASE_MIN = $PROPERTY->PROPERTY_LEASE_MIN;
    $PROPERTY_LEASE_MAX = $PROPERTY->PROPERTY_LEASE_MAX;
    $PROPERTY_NOTE = $PROPERTY->PROPERTY_NOTE;

    
    $query = "UPDATE ANDREWSDREAMLLC.property_amenity SET 
    PROPERTY_SQUARE_FEET = $PROPERTY_SQUARE_FEET,
    PROPERTY_BED = $PROPERTY_BED,
    PROPERTY_BATH = $PROPERTY_BATH,
    PROPERTY_PARKING = '$PROPERTY_PARKING',
    PROPERTY_PET_FRIENDLY = $PROPERTY_PET_FRIENDLY,
    PROPERTY_ELECTRICITY = '$PROPERTY_ELECTRICITY',
    PROPERTY_WATER_SEWAGE_TRASH = '$PROPERTY_WATER_SEWAGE_TRASH',
    PROPERTY_LEASE_MIN = '$PROPERTY_LEASE_MIN',
    PROPERTY_LEASE_MAX = '$PROPERTY_LEASE_MAX',
    PROPERTY_NOTE = '$PROPERTY_NOTE'
       WHERE PROPERTY_KEY = $PROPERTY_KEY;";


    if (mysqli_query($conn, $query))
    {
        echo "Property updated";
    }
    else 
    {
        echo "Error: " . $conn . "<br>" . mysqli_error($conn);
    }

?>