<?php

    // Get SQL Connection object
    include 'ConnectToSQL.php';
    $conn = $GLOBALS['SQL_CONN'];  

    // There are three tables per property. Update each of them 
    $PROPERTY_KEY = $_POST['PROPERTY_KEY'];

    $PROPERTY_IDENTIFIER = $_POST['PROPERTY_IDENTIFIER'];
    $PROPERTY_NAME = $_POST['PROPERTY_NAME'];
    $PROPERTY_PRICE = $_POST['PROPERTY_PRICE'];
    $PROPERTY_TYPE = $_POST['PROPERTY_TYPE'];
    $PROPERTY_STREET1_ADDRESS = $_POST['PROPERTY_STREET1_ADDRESS'];
    $PROPERTY_STREET2_ADDRESS = $_POST['PROPERTY_STREET2_ADDRESS'];
    $PROPERTY_CITY = $_POST['PROPERTY_CITY'];
    $PROPERTY_STATE = $_POST['PROPERTY_STATE'];
    $PROPERTY_COUNTRY = $_POST['PROPERTY_COUNTRY'];
    $PROPERTY_ZIP = $_POST['PROPERTY_ZIP'];
    $PROPERTY_AVAILABLE = $_POST['PROPERTY_AVAILABLE'];
    
    
    $query = "UPDATE ANDREWSDREAMLLC.property 
              values('$PROPERTY_IDENTIFIER','$PROPERTY_NAME','$PROPERTY_PRICE','$PROPERTY_TYPE','$PROPERTY_STREET1_ADDRESS','$PROPERTY_STREET2_ADDRESS','$PROPERTY_CITY','$PROPERTY_STATE','$PROPERTY_COUNTRY','$PROPERTY_ZIP', $PROPERTY_AVAILABLE,NOW())
              WHERE PROPERTY_KEY == '$PROPERTY_KEY';";

    $PROPERTY_SQUARE_FEET = $_POST['PROPERTY_SQUARE_FEET'];
    $PROPERTY_BED = $_POST['PROPERTY_BED'];
    $PROPERTY_BATH = $_POST['PROPERTY_BATH'];
    $PROPERTY_PARKING = $_POST['PROPERTY_PARKING'];
    $PROPERTY_PET_FRIENDLY = $_POST['PROPERTY_PET_FRIENDLY'];
    $PROPERTY_ELECTRICITY = $_POST['PROPERTY_ELECTRICITY'];
    $PROPERTY_WATER_SEWAGE_TRASH = $_POST['PROPERTY_WATER_SEWAGE_TRASH'];
    $PROPERTY_LEASE_MIN = $_POST['PROPERTY_LEASE_MIN'];
    $PROPERTY_LEASE_MAX = $_POST['PROPERTY_LEASE_MAX'];
    $PROPERTY_NOTE = $_POST['PROPERTY_NOTE'];
    $query = "UPDATE ANDREWSDREAMLLC.property  values('$PROPERTY_IDENTIFIER','$PROPERTY_NAME','$PROPERTY_NAME','$PROPERTY_STREET1_ADDRESS','$PROPERTY_STREET2_ADDRESS','$PROPERTY_CITY','$PROPERTY_STATE','$PROPERTY_COUNTRY','$PROPERTY_ZIP', $PROPERTY_AVAILABLE,NOW());";

    if (mysqli_query($conn, $query))
    {
        echo "Property updated";
    }
    else 
    {
        echo "Error: " . $conn . "<br>" . mysqli_error($conn);
    }

?>